allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@grandi/darwin-arm64@1.3.1'
  - '@grandi/darwin-x64@1.3.1'
  - '@grandi/linux-arm64@1.3.1'
  - '@grandi/linux-armv7l@1.3.1'
  - '@grandi/linux-x64@1.3.1'
  - '@grandi/win32-ia32@1.3.1'
  - '@grandi/win32-x64@1.3.1'
